version: '3.4'

services:
  db:
    image: mysql:5.7.16
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task-management

  app:
    build: .
    restart: always
    ports:
      - 3000:3000
    links:
      - db
    environment:
      WAIT_HOSTS: db:3306
      NODE_ENV: prod
